- [2장] 타입스크립트의 타입 시스템/재희.md
[노션](https://statuesque-beast-2cf.notion.site/2-4144996a95f14ab590104cc2c8074ba5?pvs=4)
> [2장][재희] 타입스크립트의 타입 시스템

- [2장] 타입스크립트의 타입 시스템/동호.md
[노션 원본](https://khakhid.notion.site/ch02-1-db65014414084783b5c4f3d87c36feb7)
> [2장][동호] 타입스크립트의 타입 시스템 

- [3장] 타입 추론/지윤.md
[벨로그](https://velog.io/@jiyoon2/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD-3%EC%9E%A5-%ED%83%80%EC%9E%85-%EC%B6%94)
퀴즈 #34
> [3장][지윤] 타입 추론

- [3장] 타입 추론/태호.md
[벨로그 링크](https://velog.io/@nabi5986/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-3%EC%9E%A5)
> [3장][태호] 타입 추론

- [3장] 타입 추론/진욱.md
> [3장][진욱] 타입 추론

- [3장] 타입 추론/효리.md
🔗 [노션 링크](https://artistic-roadrunner-94f.notion.site/TS-3-a33f7610749c48a4a72c99891e477130?pvs=4)
> [3장][효리] 타입 추론

- [3장] 타입 추론/동호.md
[노션 원본](https://khakhid.notion.site/ch03-dbc0ddec3b8943a0b6f1d7019df87de3?pvs=4)
> [3장][동호] 타입 추론

- [4장] 타입 설계/재희.md
[노션](https://statuesque-beast-2cf.notion.site/4-b60fa36b33f941ecb9e8face5e3ba278?pvs=4)
> [4장][재희] 타입 설계

- [4장] 타입 설계/지윤.md
[벨로그](https://velog.io/@jiyoon2/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-4%EC%9E%A5-%ED%83%80%EC%9E%85-%EC%84%A4%EA%B3%84)
#46
> [4장][지윤] 타입 설계

- [4장] 타입 설계/태호.md
[벨로그 링크](https://velog.io/@nabi5986/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-4%EC%9E%A5)
> [4장][태호] 타입 설계

- [4장] 타입 설계/진욱.md
> [4장][진욱] 타입 설계

- [4장] 타입 설계/효리.md
🔗 [노션 링크](https://artistic-roadrunner-94f.notion.site/TS-4-4280151e3f9045f29a9766b1781ac415?pvs=4)
> [4장][효리] 타입 설계

- [5장] any 다루기/지윤.md
[벨로그](https://velog.io/@jiyoon2/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-5%EC%9E%A5-any-%EB%8B%A4%EB%A3%A8%EA%B8%B0)
#58
> [5장][지윤] any 다루기

- [5장] any 다루기/진욱.md
[벨로그](https://velog.io/@dlwl98/5%EC%9E%A5-any-%EB%8B%A4%EB%A3%A8%EA%B8%B0)
퀴즈 #62
> [5장][진욱] any 다루기

- [5장] any 다루기/태호.md
[벨로그](https://velog.io/@nabi5986/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-5%EC%9E%A5)
> [5장][태호] any 다루기

- [5장] any 다루기/효리.md
🔗 [노션 링크](https://artistic-roadrunner-94f.notion.site/TS-5-bf57e9b3732a4cc38bc0fcb378c811eb?pvs=4)
> [5장][효리] any 다루기

- [6장] 타입 선언과 @types/태호.md
[벨로그](https://velog.io/@nabi5986/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-6%EC%9E%A5)
> [6장][태호] 타입 선언과 @types

- [6장] 타입 선언과 @types/효리.md
> [6장][효리] 타입 선언과 @types 

- [6장] 타입 선언과 @types/진욱.md
> [6장][진욱] 타입 선언과 @types

- [7장] 코드를 작성하고 실행하기/지윤.md
[벨로그](https://velog.io/@jiyoon2/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-7%EC%9E%A5-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%9E%91%EC%84%B1%ED%95%98%EA%B3%A0-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0)
#80
> [7장][지윤] 코드를 작성하고 실행하기

- [7장] 코드를 작성하고 실행하기/태호.md
[벨로그](https://velog.io/@nabi5986/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-7%EC%9E%A5)
> [7장][태호] 코드를 작성하고 실행하기

- [7장] 코드를 작성하고 실행하기/동호.md
**[노션 원본 링크](https://khakhid.notion.site/ch07-7c2cad57c4dd47f28ba3bc915a988576?pvs=4)**
**퀴즈 바로가기 #88**
> [7장][동호] 코드를 작성하고 실행하기 

- [7장] 코드를 작성하고 실행하기/진욱.md
[벨로그 링크](https://velog.io/@dlwl98/7%EC%9E%A5-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%9E%91%EC%84%B1%ED%95%98%EA%B3%A0-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0)
close #90
> [7장][진욱] 코드를 작성하고 실행하기
